# Generated by Django 3.2.8 on 2022-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_time',
            field=models.CharField(default='15/05/22 | 02: 50', max_length=255),
        ),
    ]
